version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: "UTC"
    assignees:
      - ChristophShyper
    groups:
      gha-all:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: "UTC"
    assignees:
      - ChristophShyper
    groups:
      docker-base-images:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /pip/common/
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: "UTC"
    assignees:
      - ChristophShyper
    groups:
      pip-common-patch-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      pip-common-major:
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: pip
    directory: /pip/aws/
    target-branch: master
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: "UTC"
    assignees:
      - ChristophShyper
    groups:
      pip-aws-patch-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      pip-aws-major:
        patterns:
          - "*"
        update-types:
          - major
