version: '3'

silent: true

includes:
  variables: ./Taskfile.variables.yml
  scripts: ./Taskfile.scripts.yml
  docker:
    taskfile: ./Taskfile.docker.yml
    flatten: true
  cicd:
    taskfile: ./Taskfile.cicd.yml
    flatten: true
  terragrunt:
    taskfile: ./Taskfile.terragrunt.yml
    flatten: true

tasks:
  default:
    desc: List tasks
    cmds:
      - task help

  help:
    desc: Detailed help
    cmds:
      - task: scripts:help
