name: (C) Dependency Update

on:
  schedule:
    - cron: 0 5 * * 3
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: read

jobs:
  check:
    name: Check for new versions
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Task
        uses: go-task/setup-task@v2
        with:
          version: 3.x

      - name: Check for new versions
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TERM: xterm-256color
        run: task dependency:update

      - name: Run linters
        run: task lint

      - name: Commit and push changes (conditional)
        if: env.VERSION_TAG != ''
        uses: devops-infra/action-commit-push@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: dependency/${{ env.VERSION_BRANCH }}
          commit_message: "chore(deps): bump ${{ env.VERSION_TAG }}"
          signing_mode: ssh
          signing_key: ${{ secrets.SSH_SIGNING_KEY }}

      - name: Get template
        run: task git:get-pr-template

      - name: Create pull request
        if: env.VERSION_TAG != ''
        uses: devops-infra/action-pull-request@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: ${{ github.event.repository.default_branch }}
          title: "chore(deps): bump ${{ env.VERSION_TAG }}"
          template: .tmp/PULL_REQUEST_TEMPLATE.md
          get_diff: true
