name: (Cron) Weekly repository health

on:
  schedule:
    - cron: 0 5 * * 1
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: read
  packages: write

jobs:
  call:
    uses: devops-infra/.github/.github/workflows/reusable-cron-check-dependencies.yml@v1
    with:
      profile: dockerized
    secrets: inherit
