name: (Manual) Sync Common Files

on:
  workflow_dispatch:
    inputs:
      type:
        description: File type to sync
        required: true
        default: all
        type: choice
        options:
          - all
          - configs
          - ignores
          - taskfiles

permissions:
  contents: write
  pull-requests: write

jobs:
  call:
    uses: devops-infra/.github/.github/workflows/reusable-manual-sync-common-files.yml@v1
    with:
      sync-type: ${{ inputs.type }}
      template-profile: dockerized
