name: Pull Request

on:
  push:
    branches-ignore:
      - 'master'
      - 'dependabot**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.2.0
        with:
          dockerfile: Dockerfile

  build-and-push:
    name: Build & push
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        flavour: [slim, plain, aws, azure, gcp]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Build & push
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1
          DOCKER_BUILDKIT: 1
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TERM: xterm-256color
          VERSION_PREFIX: test-
        run: |
          docker buildx create --use
          make login
          make push-${{ matrix.flavour }}
          docker pull ghcr.io/devops-infra/docker-terragrunt:test-${{ matrix.flavour }}-latest
          docker pull ghcr.io/devops-infra/docker-terragrunt:test-${{ matrix.flavour }}-tf-latest
          docker pull ghcr.io/devops-infra/docker-terragrunt:test-${{ matrix.flavour }}-ot-latest

      - name: Cont.Struc.Test - ${{ matrix.flavour }}
        uses: plexsystems/container-structure-test-action@v0.3.0
        with:
          image: ghcr.io/devops-infra/docker-terragrunt:test-${{ matrix.flavour }}-latest
          config: tests/${{ matrix.flavour }}.yml

      - name: Cont.Struc.Test - Terraform
        uses: plexsystems/container-structure-test-action@v0.3.0
        with:
          image: ghcr.io/devops-infra/docker-terragrunt:test-${{ matrix.flavour }}-tf-latest
          config: tests/tf.yml

      - name: Cont.Struc.Test - OpenTofu
        uses: plexsystems/container-structure-test-action@v0.3.0
        with:
          image: ghcr.io/devops-infra/docker-terragrunt:test-${{ matrix.flavour }}-ot-latest
          config: tests/ot.yml

  pull-request:
    name: Pull Request
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Template
        shell: bash
        run: |
          mkdir -p .tmp
          curl -LsS https://raw.githubusercontent.com/devops-infra/.github/master/PULL_REQUEST_TEMPLATE.md -o .tmp/PULL_REQUEST_TEMPLATE.md

      - name: Pull Request
        uses: devops-infra/action-pull-request@v0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          template: .tmp/PULL_REQUEST_TEMPLATE.md
          get_diff: true
